version: 0.1

phases:
  install:
    commands:
      - go get -v

  pre_build:
    commands:
      # Run all tests included with our application
      - go test

  build:
    commands:
      # Build our application
      - go build -o go-aws-eb

artifacts:
  files:
    - go-aws-eb
    - buildspec.yml
    # - config/*
    # - codedeploy/*
    # - cloudformation/*
