version: "3.9"
services:
  web:
    container_name: go-aws-eb
    image: "6939572736/go-aws-eb:latest"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - logs:/app/logs
    ports:
      - "80:5000"
    environment:
      - SERVICE_PORT
      - LOG_PATH
volumes:
  logs:
    external: false
