name: Go

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create ZIP deployment package
        run: zip -r go-eb-app.zip ./

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "ap-southeast-1"

      - name: Upload package to S3 bucket
        run: aws s3 cp go-eb-app.zip s3://elasticbeanstalk-ap-southeast-1-949010166236/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name go-eb-app \
          --source-bundle S3Bucket="elasticbeanstalk-ap-southeast-1-949010166236",S3Key="go-eb-app.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name go-eb-app --version-label "ver-${{ github.sha }}"
